### ISSUE TITLE
Авторизация на https://oauth20.mos.ru/sps/j_security_check

### ISSUE THREAD

**Issue by sbaikov96** [evgenyvolferts/mos.ru-php#1]
Евгений! Доброго времени суток. Хочу в своём проекте авторизоваться на данном сайте

Пробую так, юзаю библиотеку php-curl-class

```$parser = new Curl();
	$parser->setUserAgent('Mozilla/5.0 (Windows NT 6.1; WOW64; rv:61.0) Gecko/20100101 Firefox/61.0');
	$parser->setOpt(CURLOPT_FOLLOWLOCATION, true);
	$parser->setOpt(CURLOPT_RETURNTRANSFER, true);
	$parser->setHeader('Accept-Language', 'ru-RU,ru;q=0.8,en-US;q=0.5,en;q=0.3');
	$parser->setHeader('Content-Type', 'application/x-www-form-urlencoded');
	$parser->post('https://oauth20.mos.ru/sps/j_security_check',array(
    'accessType' => 'phone',
    'j_password' => '***',
    'j_username' => '***',
));
```

но сайт на меня ругается: 

>  Неверный запрошенный URL
>  Невозможно принять запрос по неизвестному адресу https://oauth20.mos.ru/sps/.
>  Это может быть связано со следующими обстоятельствами:
 >     Запрошенный адрес не существует.
 >     Возможно вы пытаетесь войти на портал, введя адрес https://oauth20.mos.ru/sps/login.jsp в строку браузера.
>  Перейдите на страницу портала, к которому необходимо получить доступ, и нажмите на кнопку >  Войти"
>  2018-10-18T12:55:39Z

Как ты так просто авторизовался?

**Comment by evgenyvolferts** [comment]
Привет.

Обрати внимание на cookies.
