### ISSUE TITLE
Доработка

### ISSUE THREAD

**Issue by EvelRus** [evgenyvolferts/mos.ru-php#2]
Приветствую.

Два вопроса.
1. В конфиге есть настройка за Мосэнергосбыт, как-то вытащить их данные можно?
2. Можно ли в water.php добавить еще один аргумент к GET (1-3) кол-во месяцев за которые необходимо получить данные? Хочется что-то типа `php water.php get 1` и получить данные 123|75 (разделитель любой, просто | используется редко)

Можно, конечно, доработать самому, но боюсь получится монстр с регулярками и *кодом )

**Comment by evgenyvolferts** [comment]
Что-то я пропустил это сообщение)

1. Настройка параметров МосЭнергоСбыт пришла из шелл-скрипта, с которого все началось, на php я работу со счетчиками электроэнергии не реализовывал (т.к. сотрудники МосЭнергоСбыта ежемесячно сами снимают показания).
2. Вы можете использовать результат метода parseWaterCountersInfo() для обработки и вывода в нужном формате. Сейчас mos.ru возвращает показания за текущий месяц (если переданы) и три предыдущих.
